### ISSUE TITLE
@NewEpisode comment

### ISSUE THREAD

**Issue by AlexCucinelli** [phon-ca/phontalk#3]
"@"New Episode is a comment line in .cha akin to "@"Activities and "@"Comment (Not a header, differing from most lines beginning with "@")
Through converting chat->talkbank->phon->talkbank->chat, "@"New Episode becomes "@"Comment. 
In talkbank this starts as the following:

- (chat->)talkbank: result of Chatter.

![chat2talkbank](https://user-images.githubusercontent.com/30468863/28717309-ccdba61a-737b-11e7-84fd-7fb8b9121678.png)

- (talkbank->)phon: result of Phontalk. (unsure if the loss of the space is relevant to this issue)

![talkbank2phon](https://user-images.githubusercontent.com/30468863/28717367-0cebef6c-737c-11e7-8acd-d7def0650592.png)

- (phon->)talkbank: result of Phontalk. (This is the step where the distinction is lost between "@"New Episode, and what eventually becomes the generic "@"Comment)

![phon2talkbank](https://user-images.githubusercontent.com/30468863/28717501-a7bac57c-737c-11e7-8cc7-53ba8ed16bd2.png)

Note that "@"New Episode will never have any additional info, only the comment line itself, unlike "@"Activities.

**Comment by ghedlund** [comment]
This should be fixed in version 2.5, could you confirm?

**Comment by AlexCucinelli** [comment]
This is fixed in 2.6.
