### ISSUE TITLE
Using PHON and CHATTER for CHAT files

### ISSUE THREAD

**Issue by ers0040** [phon-ca/phontalk#4]
Hello,
I am a graduate research assistant working with CLAN to transcribe videos of participants in a research study. Currently I am having difficulties with using PHON and CHATTER with transcripts completed in CLAN. 
I attached a screenshot of the PHON manual in which it is stated that PHON can be used with CLAN transcriptions with CHATTER but it doesn't give any other information about making these programs work together. I would greatly appreciate any information on this.
![phon manual screenshot](https://user-images.githubusercontent.com/45945142/50098939-8f4dfb80-01e2-11e9-91f4-37d914cee137.jpg)

Thanks,
Emily Shelton

**Comment by ghedlund** [comment]
Hello Emily,

PhonTalk is an application which is used internally between our team and CHILDES for corpus conversion.  At the moment there are some issues preventing things from working smoothly and this will actually be my first priority to address in the new year.

The current version of Phon does include some preliminary support for the TalkBank (.xml) format which is produced by the Chatter application available at https://talkbank.org/software/chatter.html.

Example: 
Convert the English-Davis (https://phonbank.talkbank.org/access/Eng-NA/Davis.html) corpus for use in Phon

1) Download the 'Davis.zip' file and extract files to a new folder named 'Davis' on your hard drive.
2) Download and install the newest version of Java for your operating system (https://www.oracle.com/technetwork/java/javase/downloads/index.html)
3) Download and double-click the 'platform-independent jar' (chatter.jar) file
4) In the first column of options choose 'CHAT', in the second column choose 'XML' (should be default options)
![image](https://user-images.githubusercontent.com/866552/50149701-7dc62b80-0296-11e9-858a-f1cc5bf3d685.png)
5) From the 'File' menu, choose the 'Davis' folder created in step 1
![image](https://user-images.githubusercontent.com/866552/50149687-73a42d00-0296-11e9-9ddc-385d78ee26bc.png)
6) Wait for the process to complete, errors will be printed in the window. There will be a new folder named 'Davis-xml' next to the 'Davis' folder created in step 1.
![image](https://user-images.githubusercontent.com/866552/50149792-b2d27e00-0296-11e9-8c87-fac196a97878.png)
7) Open Phon and select 'Browse for Project' in the Welcome window.  You should see the sessions in Phon and (fingers crossed) they can be opened as Phon sessions.  After editing these sessions you have the option of saving them in Phon format (you will be prompted when saving.)

Also note that Phon uses the following file structure for projects:

 - Project Folder
   - Corpus1
       - Session1.xml
       - Session1.xml
       - ...
   - Corpus2 
       - Session3.xml
       - ...

The files in the Davis.zip folder also use the format so we could use the output from Chatter directly as a Phon project.  You can also copy the .xml files produced by Chatter into existing Phon projects.

Hope that helps, in future versions of Phon .cha files will be supported without the need for conversion.  If you have any issues please let me know.

Cheers,

-Greg
